version: '2'
services:
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    env_file:
      - .env
    volumes:
      - ./bot/:/usr/src/botapp
      - /usr/src/bot/node_modules
    links:
      - api
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    env_file:
      - .env
    volumes:
      - ./api/:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - "3000:3000"
    links:
      - redis
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  redis-data: